### ISSUE TITLE
Arrays of typed pairs not allowed in pairs

### ISSUE THREAD

**Issue by aDotInTheVoid** [RiscInside/WACC-to-C#5]
```ruby
begin
        pair(int,int) a = newpair(1,2);
        pair(int,int) b = newpair(3,4);
        pair(int,int)[] a0 = [a];
        pair(int,int)[] b0 = [b];
        pair(pair(int,int)[], pair(int,int)[]) int_4 = newpair(a0, b0);
        free(int_4);
        free(a0);
        free(b0);
        free(a);
        free(b)
end
```

This should be allowed, as a pair-elem-type can have an array-type, which in turn can have an arbityary type

![
Screanshot of a BNF grammer
type = base-type
    | array-type
    | pair-type
    ;
base-type = "int"
    | "bool"
    | "char"
    | "string"
    ;
array-type = type, "[", "]";
pair-type = "pair", "(", pair-elem-type, pair-elem-type, ")";
pair-elem-type = base-type
    | array-type
    | "pair"
    ;
](https://user-images.githubusercontent.com/28781354/168679070-4b9394e4-270e-465e-ad8b-e41584594d97.png)

However it is rejected
```
error at big_ty.wacc:6:11: unexpected token (expected ',', got '(')
```

**Comment by RiscInside** [comment]
Fixed in 882e4767a020b6be609e3065d5f7d8c276d0af61
